export { default as Dashboard } from "./Dashboard";
export { default as Signup } from "./Signup";
export { default as Login } from "./Login";
export { default as NotFound } from "./NotFound";
export { default as Privacy } from "./Privacy";
export { default as Profile } from "./Profile";
export { default as Contact } from "./Contact";
export { default as Landing } from "./Landing";
export { default as Settings } from "./Settings";
export * from "./Wallet";
