import React from 'react';
import tw from "twin.macro";
import { Text, HeadingRow, Heading, MainNavbar, Footer, PageAnimationWrapper } from "components";
import { Link } from 'react-router-dom';

const Container = tw.div`px-5 mx-auto py-12  lg:p-24 text-gray-900 bg-gray-100`;

const PrivacyPage = () => {

    return (
        <PageAnimationWrapper>
            <MainNavbar />
            <Container>
                <HeadingRow>
                    <Heading>Privacy Policy</Heading>
                </HeadingRow>
                <Text>
                    <p>Last updated: August 5th, 2021</p>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
                        of Your information when You use the Service and tells You about Your privacy rights and how
                        the law protects You.
                    </p>
                    <p>
                        We use Your Personal data to provide and improve the Service. By using the Service, You
                        agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h1>Interpretation and Definitions</h1>
                    <h2>Interpretation</h2>
                    <p>
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.
                    </p>
                    <h2>Definitions</h2>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul>
                        <li>
                            <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our
                                Service.
                            </p>
                        </li>
                        <li>
                            <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                                refers to Afkanerd Ltd, Bamenda.
                            </p>
                        </li>
                        <li>
                            <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
                                device by a website, containing the details of Your browsing history on that website
                                among its many uses.
                            </p>
                        </li>
                        <li>
                            <p><strong>Country</strong> refers to: Cameroon
                            </p>
                        </li>
                        <li>
                            <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
                                or a digital tablet.
                            </p>
                        </li>
                        <li>
                            <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                            </p>
                        </li>
                        <li>
                            <p><strong>Service</strong> refers to the Website.
                            </p>
                        </li>
                        <li>
                            <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                                of the Company. It refers to third-party companies or individuals employed by the
                                Company to facilitate the Service, to provide the Service on behalf of the Company, to
                                perform services related to the Service or to assist the Company in analyzing how the
                                Service is used.
                            </p>
                        </li>
                        <li>
                            <p><strong>Third-party Social Media Service</strong> refers to any website or any social network website
                                through which a User can log in or create an account to use the Service.
                            </p>
                        </li>
                        <li>
                            <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                                Service or from the Service infrastructure itself (for example, the duration of a page visit).
                            </p>
                        </li>
                        <li>
                            <p><strong>Website</strong> refers to SMSwithoutborders, accessible from https://smswithoutborders.com
                            </p>
                        </li>
                        <li>
                            <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
                                entity on behalf of which such individual is accessing or using the Service, as applicable.
                            </p>
                        </li>
                    </ul>

                    <h1>Collecting and Using Your Personal Data</h1>
                    <h2>Types of Data Collected</h2>
                    <h3>Personal Data</h3>
                    <p>For the purposes of registering for this service and subsequently sending and receiving SMS via
                        this service, we will require a phone number. We are not strict on the ownership of the number
                        you choose to use, but we will send an authentication message to the number so as to
                        determine you have the authority to use that number.
                    </p>
                    <p>
                        For the purposes of providing you information on local Gateways for sending SMS to, we will
                        require the country of the phone number. We do not collect data on the country of the user
                    </p>
                    <p>
                        For the purposes of sending you emails by SMS we store your email address in a hashed
                        format.
                    </p>

                    <p>Data we require from you:</p>

                    <ul>
                        <li>Phone number</li>
                        <li>Country of Phone number</li>
                    </ul>

                    <h3>Usage Data</h3>
                    <p>Usage data is collected automatically when using this service.</p>
                    <p>Usage Data is limited to:</p>
                    <ul>
                        <li>Country of Gateway requested</li>
                        <li>Timestamps</li>
                        <li>Requested service</li>
                    </ul>
                    <p>
                        Our purpose for collecting this meta data would be to produce meaningful summary data for the
                        general public.
                    </p>
                    <p>
                        Without you granting access to receive and send SMS from Us, we will not send any SMS either
                        for Advertisement or information. The only SMS we will be sending is in cases of:
                    </p>
                    <ul>
                        <li>
                            Registration for the platform: This entails sending an authentication code to the used
                            number
                        </li>
                        <li>
                            Recovery of account: This entails sending and authentication code to the used number
                        </li>
                    </ul>
                    <p>
                        In cases of account recovery, all stored data will be deleted and you are expected to redo the
                        process of storing them as you see fit.
                    </p>

                    <h3> Information from Third-Party Social Media Services</h3>
                    <p>
                        For the purposes of using third-party platforms, the website will request access to your
                        third-party platforms. The website stores the access you grant us and no other information
                        about the profile of the individual.</p>
                    <p>
                        Due to the ability of users to store multiple access for the same third-party platforms we store
                        unique profile handles per platform to aid the user in identifying which account they are currently
                        using.
                    </p>
                    <p>
                        We do not use third-party identifiable information for tracking, identifying or categorizing users.
                    </p>

                    <h2>Security of Your Personal Data</h2>
                    <p>
                        The security of Your Personal Data is important to Us, but remember that no method of
                        transmission over the Internet, or method of electronic storage is 100% secure. While We strive
                        to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its
                        absolute security.
                    </p>

                    <h2>Opting out and data deletion</h2>
                    <p>
                        You can opt out of our service at will. This will trigger a complete deletion of your personal data
                        from our system immediately. We will revoke every and all access you granted to Us for the
                        usage of this product upon deletion. We can only delete personal data we have stored on our
                        database. Deletion of personnel from other third party databases even if linked from our service
                        will have to be requested directly from the third party. We provide information on how to perform
                        this for each third party service we provide.
                    </p>

                    <h2>Children's Privacy</h2>
                    <p>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect
                        personally identifiable information from anyone under the age of 13. If You are a parent or

                        guardian and You are aware that Your child has provided Us with Personal Data, please contact
                        Us. If We become aware that We have collected Personal Data from anyone under the age of
                        13 without verification of parental consent, We take steps to remove that information from Our
                        servers.
                    </p>
                    <p>
                        If We need to rely on consent as a legal basis for processing Your information and Your country
                        requires consent from a parent, We may require Your parent's consent before We collect and
                        use that information.
                    </p>

                    <h2>Links to Other Websites</h2>
                    <p>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a
                        third party link, You will be directed to that third party's site. We strongly advise You to review the
                        Privacy Policy of every site You visit.</p>
                    <p>
                        We have no control over and assume no responsibility for the content, privacy policies or
                        practice s of any third party sites or services.
                    </p>

                    <h2>Changes to this Privacy Policy</h2>
                    <p>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by
                        posting the new Privacy Policy on this page.</p>
                    <p>
                        We will let You know via email and/or a prominent notice on Our Service, prior to the change
                        becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                    <p>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this
                        Privacy Policy are effective when they are posted on this page.</p>

                    <h2>Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, You can contact us
                        <ul>
                            <li>
                                <span>By visiting this page on our website </span>
                                <Link
                                    to="/contact-us"
                                    tw="text-primary-900"
                                >
                                    Contact Us
                                </Link>
                            </li>
                        </ul>
                    </p>
                </Text>
            </Container>
            <Footer />

        </PageAnimationWrapper >
    );
}

export default PrivacyPage;